# Docker Compose стек для микрофронтенда "landing" (Next.js)
# Базовый реестр образов: ghcr.io/OWNER/REPO  (оставлено в комменте для читаемости)

services:
  landing:
    image: ${IMAGE_REPO}:${IMAGE_TAG}
    container_name: landing
    restart: unless-stopped
    env_file:
      - /opt/garmonia/landing.env
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.docker.network=web

      # правило по домену (две зоны — через OR)
      - traefik.http.routers.landing.rule=(Host(`garmoniamira.pro`) || Host(`www.garmoniamira.pro`)) && PathPrefix(`/`) && !PathPrefix(`/directus`)

      # entrypoints: http + https
      - traefik.http.routers.landing.entrypoints=web,websecure

      # TLS от Let's Encrypt (резолвер "le")
      - traefik.http.routers.landing.tls=true
      - traefik.http.routers.landing.tls.certresolver=le

      # basic-auth + noindex
      - traefik.http.routers.landing.middlewares=landing-auth,landing-noindex
      - traefik.http.middlewares.landing-auth.basicauth.usersfile=/etc/traefik/extras/landing.htpasswd
      - traefik.http.middlewares.landing-auth.basicauth.realm=Restricted
      - traefik.http.middlewares.landing-noindex.headers.customresponseheaders.X-Robots-Tag=noindex, nofollow, noarchive

      - traefik.http.services.landing.loadbalancer.server.port=3000
    networks:
      - web

networks:
  web:
    external: true


