# Docker Compose стек для микрофронтенда "landing" (Next.js)
# Базовый реестр образов: ghcr.io/OWNER/REPO  (оставлено в комменте для читаемости)

services:
  landing:
    image: ${IMAGE_REPO}:${IMAGE_TAG}
    container_name: landing
    restart: unless-stopped
    env_file:
      - /opt/garmonia/landing.env
    environment:
      - NODE_ENV=production
    # Если нужен прямой проброс порта (без внешнего прокси)
    # Поменяйте левую часть на нужный порт хоста
    labels:
      - traefik.enable=true
      - traefik.docker.network=web

      # роутинг по домену лендинга
      - traefik.http.routers.landing.entrypoints=web
      - traefik.http.routers.landing.rule=Host(`garmoniamira.pro`,`www.garmoniamira.pro`) && PathPrefix(`/`) && !PathPrefix(`/directus`)

      # basic-auth (файл внутри контейнера Traefik)
      - traefik.http.routers.landing.middlewares=landing-auth,landing-noindex
      - traefik.http.middlewares.landing-auth.basicauth.usersfile=/etc/traefik/extras/landing.htpasswd
      - traefik.http.middlewares.landing-auth.basicauth.realm=Restricted

      # закрыть от индексации
      - traefik.http.middlewares.landing-noindex.headers.customresponseheaders.X-Robots-Tag=noindex, nofollow, noarchive

      # порт сервиса
      - traefik.http.services.landing.loadbalancer.server.port=3000
    networks:
      - web

networks:
  web:
    external: true


