# Docker Compose стек для микрофронтенда "landing" (Next.js)
# Базовый реестр образов: ghcr.io/OWNER/REPO  (оставлено в комменте для читаемости)

services:
  landing:
    image: ${IMAGE_REPO}:${IMAGE_TAG}
    container_name: landing
    restart: unless-stopped
    env_file:
      - /opt/garmonia/landing.env
    environment:
      - NODE_ENV=production
    # Если нужен прямой проброс порта (без внешнего прокси)
    # Поменяйте левую часть на нужный порт хоста
    labels:
      - traefik.enable=true
      - traefik.http.routers.landing.entrypoints=web
      - traefik.http.routers.landing.rule=PathPrefix(`/`)
      - traefik.http.services.landing.loadbalancer.server.port=3000
    networks:
      - web

networks:
  web:
    external: true


