name: landing-cicd

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/apps/landing/**'
      - '.github/workflows/cicd.yml'
      - 'frontend/package-lock.json'
      - 'deploy/**'

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: frontend-apps-landing
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute short sha
        id: vars
        run: |
          echo "sha_short=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          echo "image_tag=main-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend/apps/landing/Dockerfile
          push: true
          provenance: false
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.image_tag }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare tmp on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.YC_HOST }}
          username: ${{ secrets.YC_USER }}
          key: ${{ secrets.YC_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            rm -rf ~/garmonia_tmp && mkdir -p ~/garmonia_tmp

      - name: Copy compose & deploy script
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.YC_HOST }}
          username: ${{ secrets.YC_USER }}
          key: ${{ secrets.YC_SSH_KEY }}
          source: "deploy/landing.compose.yml,deploy/landing.deploy.sh"
          target: "garmonia_tmp"
          debug: true

      - name: Move to /opt and run deploy
        uses: appleboy/ssh-action@v1.2.0
        env:
          GH_REPOSITORY: ${{ github.repository }}
          IMAGE_TAG: ${{ needs.build_and_push.outputs.image_tag }}
          GHCR_USER: ${{ secrets.GHCR_USER || github.actor }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.YC_HOST }}
          username: ${{ secrets.YC_USER }}
          key: ${{ secrets.YC_SSH_KEY }}
          script_stop: true
          script: |
            set -euxo pipefail
            sudo mkdir -p /opt/garmonia
            sudo mv ~/garmonia_tmp/landing.compose.yml /opt/garmonia/landing.compose.yml
            sudo mv ~/garmonia_tmp/landing.deploy.sh  /opt/garmonia/landing.deploy.sh
            sudo chmod +x /opt/garmonia/landing.deploy.sh
            sudo --preserve-env=GH_REPOSITORY,IMAGE_TAG,GHCR_USER,GHCR_TOKEN \
              bash -x /opt/garmonia/landing.deploy.sh
